#!/usr/bin/env python3
import argparse
import platform
import pickle
import sys
import os.path
import random
import datetime
from collections import defaultdict

class Quote:
    def __init__(self, quote):
        self.quote = quote
        self.time = datetime.datetime.now()
    def __str__(self):
        return '\"{}\" ({})'.format(self.quote, self.time.strftime("%Y-%m-%d %H:%M"))

def print_quote(user, quote):
    print('{}: {}'.format(user, quote))

def display_quote(args, quotedict):
    user = args.user
    rand = args.random
    # Display random quote for user
    if rand:
        if not user:
            user = random.choice(list(quotedict.keys()))
        quote = random.choice(quotedict[user])
        print_quote(user, quote)
        return
    # Display all quotes for specified user
    if user:
        for quote in quotedict[user]:
            print_quote(user, quote)
        return
    else:
        for user, quotes in quotedict.items():
            for quote in quotes:
                print_quote(user, quote)

def add_quote(args, quotedict):
    user = args.user
    quote = args.quote
    quotedict[user].append(Quote(quote))
    print_quote(user, quote)

def search_quote(args, quotedict):
    phrase = args.phrase
    user = args.user
    delete = args.delete
    if delete:
        ans = input("Are you sure you want to delete all matching entries?\n")
        if ans.strip() != 'y' and ans.strip() != 'yes':
            return
    if user:
        matches = [quote for quote in quotedict[user] if phrase in quote.quote]
        for match in matches:
            print_quote(user, match)
            if delete:
                quotedict[user].remove(match)
    else:
        all_quotes = quotedict.values()
        for user, quotes in quotedict.items():
            matches = [quote for quote in quotes if phrase in quote.quote]
            for match in matches:
                print_quote(user, match)
                if delete:
                    quotedict[user].remove(match)


def main(argv=None):
    # Check os and set install location (Windows not supported)
    filename = "/var/lib/quotes/quotesdict"

    # Set up arguments
    parser = argparse.ArgumentParser(description='Save and view quotes.')
    subparsers = parser.add_subparsers(dest='command', help='command to run')
    subparsers.required = True
    parser_display = subparsers.add_parser('display', help='display a quote')
    parser_display.add_argument('--user', help='choose user to display')
    parser_display.add_argument('--random', action='store_true', help='pick a random quote')

    parser_add = subparsers.add_parser('add', help='add a quote')
    parser_add.add_argument('user', help='specify quote speaker')
    parser_add.add_argument('quote', help='quote to add')

    parser_search = subparsers.add_parser('search', help='search for a quote')
    parser_search.add_argument('phrase', help='search for phrase in quotes')
    parser_search.add_argument('--user', help='limit search to user')
    parser_search.add_argument('--delete', action='store_true', help='limit search to user')

    parser_display.set_defaults(func=display_quote)
    parser_add.set_defaults(func=add_quote)
    parser_search.set_defaults(func=search_quote)
    args = parser.parse_args()
    # Check if quotes file exists, if not then make new
    if os.path.exists(filename):
        quotefile = open(filename,'rb')
        quotedict = pickle.load(quotefile)
        quotefile.close()
    else:
        quotedict = defaultdict(list)

    args.func(args, quotedict)

    # Pickle and finish
    with open(filename, "wb") as f:
        pickle.dump(quotedict,f)
    return

if __name__ == '__main__':
        sys.exit(main())
